<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Posts
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getPosts() Returns the current record's "Posts" collection
 * @method Category            setName()  Sets the current record's "name" value
 * @method Category            setPosts() Sets the current record's "Posts" collection
 * 
 * @package    training
 * @subpackage model
 * @author     Muhammadali Shaduli
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as Posts', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}