<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $body
 * @property string $author
 * @property boolean $is_approved
 * @property integer $category_id
 * @property Category $Category
 * 
 * @method string   getTitle()       Returns the current record's "title" value
 * @method string   getBody()        Returns the current record's "body" value
 * @method string   getAuthor()      Returns the current record's "author" value
 * @method boolean  getIsApproved()  Returns the current record's "is_approved" value
 * @method integer  getCategoryId()  Returns the current record's "category_id" value
 * @method Category getCategory()    Returns the current record's "Category" value
 * @method Post     setTitle()       Sets the current record's "title" value
 * @method Post     setBody()        Sets the current record's "body" value
 * @method Post     setAuthor()      Sets the current record's "author" value
 * @method Post     setIsApproved()  Sets the current record's "is_approved" value
 * @method Post     setCategoryId()  Sets the current record's "category_id" value
 * @method Post     setCategory()    Sets the current record's "Category" value
 * 
 * @package    training
 * @subpackage model
 * @author     Muhammadali Shaduli
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 1000, array(
             'type' => 'string',
             'notblank' => true,
             'minlength' => 25,
             'length' => 1000,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}