<?php

/**
 * sfGuardPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    training
 * @subpackage model
 * @author     Muhammadali Shaduli
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardPermission extends PluginsfGuardPermission
{
}
