<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/06 15:46:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=training',
  'username' => 'root',
  'password' => 'illuali',
  'name' => 'doctrine',
)),);
